spring:
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
springdoc:
  swagger-ui:
    path: /v1/swagger.html
aws:
  sns:
    region: sa-east-1
    topic-arn: arn:aws:sns:sa-east-1:511076607674:ibico-sms-topic
server:
  tomcat:
    max-swallow-size: -1
---

release:
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ecommerce
    username: anakin
    password: kenobi
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
---

dev:
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ibico
    username: anakin
    password: kenobi

  jpa:
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: validate
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.MySQLDialect
    properties:
      hibernate:
        search:
          backend:
            directory:
              root: /Users/Guilh/.ibico/indexes
  logging:
    level:
      org.hibernate.SQL: debug
      org.springframework: debug