services:
  db:
    image: mysql:latest
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: therootdoesntexists
      MYSQL_DATABASE: ibico
      MYSQL_USER: anakin
      MYSQL_PASSWORD: kenobi
